name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

permissions:
  contents: write # Allow the workflow to write to the gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx myst-parser sphinx-rtd-theme sphinx-autodoc-typehints # Add any other extensions you use in conf.py here

      - name: Build Sphinx documentation
        run: |
          cd docs/ # Navigate into your docs directory
          make html # Run the make command to build HTML

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html # The directory where Sphinx built the HTML
          publish_branch: gh-pages # GitHub Pages will serve from this branch