# To enable Dependabot updates, create a dependabot.yml file in your .github directory.
# See https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for pip (Python)
  - package-ecosystem: "pip"
    directory: "/" # Location of your requirements.txt
    schedule:
      interval: "weekly" # Check for updates weekly
    # Allow Dependabot to create pull requests for minor and patch updates
    # major updates might need manual review
    open-pull-requests-limit: 10 # Limit open PRs
    reviewers:
      - @your-github-username # Assign yourself or a team for review
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "deps"
      include: "scope"

  # You could add more ecosystems here, e.g., for Docker if you use custom Dockerfiles
  # - package-ecosystem: "docker"
  #   directory: "/.devcontainer" # Location of your Dockerfile
  #   schedule:
  #     interval: "monthly"
